services:
  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - /home/lostlang/ollama/ollama:/root/.ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    networks:
      - ollama-docker
  ollama-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - WEBUI_AUTH=false
      - WEBUI_SECRET_KEY=
    volumes:
      - /home/lostlang/ollama/ollama-webui:/root/.ollama
    restart: unless-stopped
    ports:
      - 11435:8080
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
